apiVersion: v1
kind: Service
metadata:
  name: %SERVICE_NAME%-%NAMESPACE_NAME%
  namespace: %NAMESPACE_NAME%
  labels:
    app: %SERVICE_NAME%-%NAMESPACE_NAME%
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
spec:
  selector:
    app: %SERVICE_NAME%-%NAMESPACE_NAME%
  type: NodePort
  ports:
    - name: my-https-port
      protocol: TCP
      port: 443
      targetPort: 3000
    - name: my-http-port
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: default-port
      protocol: TCP
      port: 3000
      targetPort: 3000
