apiVersion: v1
kind: Service
metadata:
  name: ninjamart-fe-uat
  namespace: uat
  labels:
    app: ninjamart-fe-uat
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
  selector:
    app: ninjamart-fe-uat

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninjamart-fe-uat
  namespace: uat
  labels:
    app: ninjamart-fe-uat
spec:
  selector:
    matchLabels:
      app: ninjamart-fe-uat
      tier: web
  template:
    metadata:
      labels:
        app: ninjamart-fe-uat
        tier: web
    spec:
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      imagePullSecrets:
      - name: svc-devops-stg
      containers:
      - name: ninjamart-fe-uat
        image: gcr.io/eternal-empire-349717/ninjamart-fe:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

